name: Build
on:
  push:
    tags:
      - v*
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip libime-bin
          python -m pip install --use-pep517 -r requirements.txt
      - name: Merge texts
        run: |
          python scripts/merge_texts.py text output/merged_texts --enable_shouxing --enable_rime --enable_rime_flypy
      - name: build dictionary
        run: |
          libime_pinyindict output/merged_texts_ime.txt merged_texts.dict -v
      - name: Compress dictionary
        run: |
          tar -czvf merged_texts.dict.tar.gz merged_texts.dict output/*
          zip -9 merged_texts.dict.zip merged_texts.dict output/*
      - name: Upload tar.gz to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: merged_texts.dict.tar.gz
          asset_name: merged_texts.dict.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: merged_texts.dict.zip
          asset_name: merged_texts.dict.zip
          tag: ${{ github.ref }}
          overwrite: true
