name: Build
on:
  push:
    tags:
      - v*
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip libime-bin
          python -m pip install --use-pep517 -r requirements.txt
      - name: Merge texts
        run: |
          python scripts/merge_texts.py text output/merged_texts --enable_shouxing --enable_rime --enable_rime_flypy --enable_qqpinyin
      - name: build dictionary
        run: |
          libime_pinyindict output/merged_texts_ime.txt merged_texts.dict -v
      - name: Compress dictionary
        run: |
          zip -9 merged_texts.dict.zip merged_texts.dict
          zip -9 merged_texts_rime.zip output/merged_texts_rime.txt
          zip -9 merged_texts_rime_flypy.zip  output/merged_texts_rime_flypy.txt
          zip -9 merged_texts_shouxing.zip  output/merged_texts_shouxing.txt
          zip -9 merged_texts_only.zip  output/merged_texts_only.txt
          zip -9 merged_texts_qq.zip  output/merged_texts_qq.txt
          zip -9 merged_texts_ime.zip  output/merged_texts_ime.txt
      - name: Upload dict zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: merged_texts.dict.zip
          asset_name: merged_texts.dict.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload rime zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: merged_texts_rime.zip
          asset_name: merged_texts_rime.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload rime flypy zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: merged_texts_rime_flypy.zip
          asset_name: merged_texts_rime_flypy.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload shouxing zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: merged_texts_shouxing.zip
          asset_name: merged_texts_shouxing.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload only zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: merged_texts_only.zip
          asset_name: merged_texts_only.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload qq zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: merged_texts_qq.zip
          asset_name: merged_texts_qq.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload ime zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: merged_texts_ime.zip
          asset_name: merged_texts_ime.zip
          tag: ${{ github.ref }}
          overwrite: true
